### ISSUE TITLE
I'm requesting to help maintain this project

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/phpmailer#3]
As the subject says.

@herbdool I know you asked my if I was willing to maintain or co-maintain this when you ported it, and at that time, I didn't really have enough interest or time to do so, but now I at least have the interest.

**Comment by herbdool** [comment]
@oadaeh for sure, please feel free to add yourself as a co-maintainer. I haven't used this much so it's probably neglected.

**Comment by oadaeh** [comment]
Hi @herbdool. Would you mind merging in the [PR](#6)?

**Comment by herbdool** [comment]
Done

**Comment by oadaeh** [comment]
Thank you!

**Comment by herbdool** [comment]
You're welcome! I tend to miss a lot of notifications unless I'm mentioned. Happy to see you take this on.
